module AllOverIt
  module Patterns
    module ChainOfResponsibility
      class ChainOfResponsibilityHandler
        @next_handler: ChainOfResponsibilityHandler?

        def next_handler: (ChainOfResponsibilityHandler?) ?{ (?) -> untyped? } -> ChainOfResponsibilityHandler

        def handle: (untyped) -> untyped?
      end
    end
  end
end