# See the writing guide of rbs: https://github.com/ruby/rbs#guides

module AllOverIt
  module Patterns
    module ChainOfResponsibility
      VERSION: String

      def self.compose: (*ChainOfResponsibilityHandler | singleton(ChainOfResponsibilityHandler)) -> ChainOfResponsibilityHandler
    end
  end
end
