# See the writing guide of rbs: https://github.com/ruby/rbs#guides

module AllOverIt
  module Utils
    VERSION: String

    def self.as_instance: (untyped | class) -> untyped

    def self.ensure_instance_includes: (untyped, class) -> untyped

    def self.ensure_instance_is_a: (untyped, class) -> untyped
  end
end
