# See the writing guide of rbs: https://github.com/ruby/rbs#guides

module AllOverIt
  module Utils
    VERSION: String

    def self.as_instance: (instance_or_class: untyped | class) -> untyped

    def self.ensure_instance_includes: (instance: untyped, class_type: class) -> untyped

    def self.ensure_instance_is_a: (instance: untyped, class_type: class) -> untyped
  end
end
