AllCops:
  TargetRubyVersion: 3.0

  Exclude:
    - "demos/**/*.rb"
    - "spec/**/*.rb"

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
