# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in alloverit-patterns-chain_of_responsibility.gemspec
gemspec

group :development, :test do
  gem "rake", "~> 13.0"
  gem "rspec", "~> 3.0"
  gem "rubocop", "~> 1.21"
  gem "simplecov", require: false
end
