# frozen_string_literal: true

require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)

require "rubocop/rake_task"

RuboCop::RakeTask.new

task default: %i[spec rubocop]

task :tests do
  sh "bundle exec rspec"
end

task :tests_verbose do
  sh "bundle exec rspec --format documentation"
end

task :run_demo1 do
  ruby "demos/demo1/demo1.rb"
end

task :run_demo2 do
  ruby "demos/demo2/demo2.rb"
end
