module AllOverIt
  module Patterns
    module Specification
      class AlwaysTrueSpecification
        def initialize: () -> AlwaysTrueSpecification
        def satisfied_by?: (untyped) -> bool
        def to_s: () -> String
      end
    end
  end
end
