module Alloverit
  module Patterns
    module Specification
      class AndNotSpecification
        @left: Specification
        @right: Specification

        def initialize: (Specification left, Specification right) -> AndNotSpecification
        def satisfied_by?: (untyped candidate) -> bool
      end
    end
  end
end
