module Alloverit
  module Patterns
    module Specification
      class AndNotSpecification
        @left: Specification
        @right: Specification

        def initialize: (left: Specification, right: Specification) -> AndNotSpecification

        def satisfied_by?: (candidate: untyped) -> bool
      end
    end
  end
end
