module Alloverit
  module Patterns
    module Specification
      class CompositeSpecification
        def self.and: (other: Specification | [class, Specification]) -> AndSpecification

        def self.and_not: (other: Specification | [class, Specification]) -> AndNotSpecification

        def self.or: (other: Specification | [class, Specification]) -> OrSpecification

        def self.or_not: (other: Specification | [class, Specification]) -> OrNotSpecification

        def self.not: -> NotSpecification
      end
    end
  end
end
