module AllOverIt
  module Patterns
    module Specification
      class NotSpecification
        @specification: Specification

        def initialize: (specification: Specification) -> NotSpecification

        def satisfied_by?: (candidate: untyped) -> bool
      end
    end
  end
end
