module AllOverIt
  module Patterns
    module Specification
      class OrSpecification
        @left: Specification
        @right: Specification

        def initialize: (left: Specification, right: Specification) -> OrSpecification

        def satisfied_by?: (candidate: untyped) -> bool
      end
    end
  end
end
