# See the writing guide of rbs: https://github.com/ruby/rbs#guides

module Alloverit
  module Patterns
    module Specification
      def satisfied_by?: (candidate: untyped) -> bool

      def and: (other: Specification | [class, Specification]) -> Specification

      def and_not: (other: Specification | [class, Specification]) -> Specification

      def or: (other: Specification | [class, Specification]) -> Specification

      def or_not: (other: Specification | [class, Specification]) -> Specification

      def not: -> Specification
    end
  end
end
