# See the writing guide of rbs: https://github.com/ruby/rbs#guides

module Alloverit
  module Patterns
    module Specification
      def satisfied_by?: (candidate: untyped) -> bool

      def and: (other: Specification | [class, Specification]) -> AndSpecification

      def and_not: (other: Specification | [class, Specification]) -> AndNotSpecification

      def or: (other: Specification | [class, Specification]) -> OrSpecification

      def or_not: (other: Specification | [class, Specification]) -> OrNotSpecification

      def not: -> NotSpecification
    end
  end
end
