module AllOverIt
  module Patterns
    class OrNotSpecificationActiveRecord
      include SpecificationActiveRecord
      @left: SpecificationActiveRecord
      @right: SpecificationActiveRecord

      def initialize: (left: SpecificationActiveRecord, right: SpecificationActiveRecord) -> OrNotSpecificationActiveRecord
      def satisfied_by?: (candidate: untyped) -> bool
      def to_scope: (relation: untyped) -> untyped
      def to_s: () -> String
    end
  end
end
